### ISSUE TITLE
Automate creation of New Relic license keys and IDs

### ISSUE THREAD

**Issue by aaronbassett** [newrelic-experimental/netlify-plugin#6]
## Summary

From a discussion in New Relic internal Slack:

> One of the features I would like to add is the ability for users to choose (via the config) to either:
> ### Supply just an app name and a New Relic user key
> The plugin would during the build use Nerd Graph to either find the required app ids/license keys, or if not found, create them.
> 
> **Pro:** requires less configuration by the user, more streamlined.
> **Con:** there is no way to persist the keys between builds on Netlify so we would need to look up the keys each build adding a dependency between Netlify and New Relic in order for the build to complete successfully. Any network issues between us and them could cause delayed or even failed builds.
> ### Supply the required ids/keys (the current method)
> Same as it is now.
> 
> **Pro:** no dependency between us. No need to make network I/O during builds.
> **Con:** requires more configuration by the user, they probably already need to be a New Relic user to be able to complete configuration smoothly

## Tasks

- [ ] Update code
- [ ] [Update blog post](https://newrelic.com/blog/nerdlog/jumpstart-your-jamstack-monitoring)
- [ ] [Update README](https://github.com/newrelic-experimental/netlify-plugin#readme)
- [ ] Ask Netlify to update [their blog post](https://www.netlify.com/blog/netlify-and-new-relic-plugin-quickstart)

**Comment by aaronbassett** [comment]
> there is no way to persist the keys between builds on Netlify

Could we use the [plugin cache](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#plugin-methods)?
